### ISSUE TITLE
Status check for PR to depend on issues

### ISSUE THREAD

**Issue by JasonEtco** [probot/ideas#1]
In a PR, you write something like

```
/depends on #23, #24
```

to show that the PR can only be merged if those issues have been closed. So the bot will have a status check (like CI) if any of those issues are still open. If they are, the "test" is considered failed, so the PR's status will be ❌.

cc @wilhelmklopp

**Comment by ahmed-taj** [comment]
Here is my attempt https://github.com/ahmed-taj/dep

**Comment by bkeepers** [comment]
So great! Nice work on both the app and the blog post.

**Comment by ahmed-taj** [comment]
@bkeepers glad you like it, thank you!
