### ISSUE TITLE
Sign CLA on first issue interaction?

### ISSUE THREAD

**Issue by larseggert** [probot/ideas#109]
There are a bunch of CLA bots (e.g., [cla-bot](https://github.com/finos/cla-bot) or [cla-assistant](https://github.com/cla-assistant/cla-assistant)) that automate signing of CLAs for PRs.

However, none of them seems configurable to prompt a user to sign the CLA when they first interact on any **issue**? Is there a probot app  to do this?

(Background: we're increasingly using repos for IETF work, where issue discussion replaces email discussion, and it would be great if we had an active indication that a participant had acknowledged the IETF Note Well.)

**Comment by gr2m** [comment]
I'm not aware of any. Did you ask about that feature in the repositories of the two bots? Maybe they can add it as an feature, or directly you an alternative?

If they are not open to add the feature themselves, maybe you can fork it and run your own bot?

**Comment by larseggert** [comment]
`cla-bot` is looking into [adding this](https://github.com/finos/cla-bot/issues/188).
