### ISSUE TITLE
بانک جهانی

### ISSUE THREAD

**Issue by saeidasade321** [probot/ideas#116]
@ملاحظات برنامه به زبان فادگرسی ارایه شود برای,هدفهای که در پیش داریم بدون مخدودیت 
و ترجمه کامل به کل زبانها انجام گردد
@ Program considerations to be presented in the language of Fadgarsi for, the goals that we have in front of us without any restrictions
 And complete translation into all languages

**Comment by saeidasade321** [comment]
@درحال تنظیمات

**Comment by gr2m** [comment]
Is this an idea for Probot, or GitHub itself?

**Comment by saeidasade321** [comment]
@هدف ما برابری و یکسان بودن تمام مردم جهان در امر بانکی هست ولی من هنوز نتوانستم از کشورم ایران یک کارت بانکی اضافه کنم به دلیل تحریم های یک طرفه امریکا علیه کشور ایران هست ما شهروندان عادی نمایندگانی از تمامی کشورها خواهیم گذاشت که هم در حوزه امنیت تروریسم و به هدر رفتن منابع مالی جهانی و امنیت کل دارایی جهان به دست کارشناسان زبده خواهیم سپرد و هم از دعواهای 
 سیاسی در اموربانکی دوری خواهیم کرد و شهروندان عادی در تمام جهان صاحب یک ارز خاص خواهند شد که در هر جای کره خاکی که سفر کنند این ارز یکسان خواهد بود و تغییری نخواهد کرد این هدف ما برای مبارزه با پولشویی و مبارزه با تروریسم و مبارزه با سرمایه داری عده ای اندک که پول را به چنگ آورده اند و خود تصمیم میگیرند چکاری انجام دهند بدون مشورت مردم جهان یا نمایندگان آنها مبارزه با پولشویی باید جدا از اختلافات سیاسی و عقیده ای باشد تا ظلم از بین برود و همه با هم ثروتمند میشویم پس دوستان عزیز تا میتوانید اول به اهداف فکر کنید سپس کدهای خود را ارائه کنید برنامه با ید بصورت کاملا ساده در عین حال کاملا امن و محکم به سوی ارز دیحیتال حرکت کند لطفا سرعت خود را چند برابر کنید و از مدیر گیت هاب تقاضا دارم مبلغی برای توسعه دهندگان در ایران و وسایل مورد نیاز برای پیشرفت پروژه مبلغی خاص از حامیان مالی درخواست کنند تا بتوانیم هر چه  سریعتر یک ارز واحد ایجاد کنیم و فقر را ریشه کن کنیم لطفا برای حمایت مالی به ایمیل من پیغام دهید و در نظر داشته باشید من از ایران هستم که تحریم های بانکی علیه این کشور اعمال میشود و راه حلی ایجاد کنند تا بودجه مورد نظر برای پروژه تامین شود باسپاس از شما سعید عبدالخانی از ایران هستم.

**Comment by saeidasade321** [comment]
@Our goal is the equality of all people in the world in banking, but I have not yet been able to add a bank card from my country, Iran, due to US unilateral sanctions against Iran. We, ordinary citizens, will leave representatives from all countries, including  We will hand over the security of terrorism and the waste of global financial resources and the security of the entire world assets to the best experts, as well as from disputes.
  We will avoid politics in banking, and ordinary citizens around the world will have a special currency that will be the same wherever they travel on the planet and will not change. This is our goal to fight money laundering and fight terrorism and fight terrorism.  Capitalism The few who have seized money and decide for themselves what to do without consulting the people of the world or their representatives. The fight against money laundering must be separated from political and ideological differences so that oppression disappears and we all get rich.  Dear friends, as soon as you can, think about the goals, then present your codes. The program should move to digital currency in a completely simple, yet safe and solid way. Please increase your speed, and I am asking the GateHub manager for money.  Developers in Iran and the tools needed to develop the project should ask for a special amount of sponsors so that we can create a single currency and eradicate poverty as soon as possible. Please send me an email for financial support and keep in mind that I am from  I am Iran that banking sanctions are imposed against this country and R.  Let them create a solution to provide the desired budget for the project. Thank you, Saeed Abdolkhani, from Iran.

**Comment by gr2m** [comment]
we cannot help you with that sorry
