### ISSUE TITLE
Automatically protect branches that follow a certain pattern

### ISSUE THREAD

**Issue by jonico** [probot/ideas#16]
While there are [commercial offerings](https://gitmonitor.com/) to automatically protect branches that follow a certain naming pattern, I did not find an Open Source solution for this yet. Solutions like [Zappr](https://github.com/zalando/zappr) already enforce all kind of rules for already protected branches (like n-eye principle and commit message patterns), but the actual branches have to be protected manually.

The idea would be to have a Probot module that would read its configuration out of a config file in the repositories in question and registers for branch creation events. Whenever a new branch gets created it would check whether the branch name is matching a regular expression specified in the config file.

In later version of this Probot module, one may have more config options per naming pattern (regular expression), e.g. the required status checks, review and code ownership enforcements, the requirement to catch up with the target branch before a merge can happen, etc.

**Comment by jonico** [comment]
@JasonEtco: maybe an addition to https://github.com/probot/settings 😄

**Comment by C-PET** [comment]
Interested to know if this was something that was completed

**Comment by travi** [comment]
See https://github.com/probot/settings/issues/87

**Comment by jonico** [comment]
@C-PET: We also just rolled out protected branch patterns 🎉 

![image](https://user-images.githubusercontent.com/1872314/43719760-df83a468-998e-11e8-833c-ee6cd13674a3.png)

**Comment by JasonEtco** [comment]
I'm going to close this issue since its now built-in to GitHub 🎉 Thanks everyone for your ✨ feedback! Really excited to see this as a part of the platform!

**Comment by C-PET** [comment]
I see the settings setup.  However when I go to “INSTALL THE APP” it only allows for on github.com.   We have an on-prem github instance not public facing.

**Comment by JasonEtco** [comment]
@C-PET GitHub Apps are registered on an instance, so you'll need to create and deploy your own for GitHub Enterprise. [Check out our docs](https://probot.github.io/docs/github-api/#github-enterprise) for more info.

**Comment by C-PET** [comment]
Right after I sent that email I saw that deploy section.

Thank you again.
