### ISSUE TITLE
Add label to issue when a PR is associated

### ISSUE THREAD

**Issue by domcorvasce** [probot/ideas#20]
So when I add a PR for the issue N then this issue gets a label like `pr-available`, `pr-merged` or `pr-refused` (depending on the PR state).

**Comment by aishanya11** [comment]
Really interested in implementing this idea, will like to work on it.
P.S: Rgsoc aspirant. Will like to include this idea in my proposal. Team- dotJS

**Comment by domcorvasce** [comment]
Feel free to work on it

**Comment by rsarky** [comment]
Hey @domcorvasce 
Check this out :smile: 

https://github.com/apps/helpr

**Comment by domcorvasce** [comment]
That's really cool! 🎉
