### ISSUE TITLE
One newcomer issue per aspiring contributor

### ISSUE THREAD

**Issue by Rahmeen14** [probot/ideas#28]
A bot that ensures exactly one newcomer issue is assigned per person so that it’s fair for all newcomers. Additionally, it encourages the no-more-newcomers to take up challenging issues once they’re comfortable with the workflow after having tackled a newcomer issue.

P.S. I'm an aspiring RGSoC 2018 scholar and would like to work on it if it's approved.

**Comment by evertonfraga** [comment]
Related to: https://github.com/probot/ideas/issues/8. contributions are welcome.

**Comment by Rahmeen14** [comment]
Hi @evertonfraga . Thank you for the response. So does this idea stand approved?

**Comment by gr2m** [comment]
I think the [auto-assigner bot](https://github.com/evertonfraga/probot-auto-assigner) is to assign maintainers, this issue suggested by Rahmeen is to make sure that new contributors cannot take more than one issue reserved for new contributors?

I think it’s a cool idea. @Rahmeen14 can you explain in more detail how you’d make it work?

**Comment by Rahmeen14** [comment]
Hi! So our idea (my teammate's and mine) would be to flash a "you can't do it" in the comments section of the issue whenever a non-new-comer attempts to get assigned to himself another new comer issue,i.e., after having solved one new-comer-issue already in the past

**Comment by Rahmeen14** [comment]
We have resolved this issue as a part of RGSoC! 
Here's a link to the repository https://github.com/probot/first-timers-only-app
