### ISSUE TITLE
Interested to work on "Automatically merge pull requests that pass all checks"

### ISSUE THREAD

**Issue by mritunjaygoutam12** [probot/ideas#34]
Hello Everyone,
I am Mritunjay goutam from India. I am javascript developer working nodejs and last year GSOC student.
I wanna work on "Automatically merge pull requests that pass all checks".
Where to discuss more about this project idea?

**Comment by gr2m** [comment]
let's discuss at https://github.com/probot/ideas/issues/22 :)

**Comment by gr2m** [comment]
oh please excuse my manners. Welcome to Probot 👋
