### ISSUE TITLE
Voting system for issues 

### ISSUE THREAD

**Issue by vaibhavchellani** [probot/ideas#42]
In large repos  the maintainers usually have to go through a lot of issues , some of which are legit whereas others are very trivial or don`t require the immediate attention of maintainers and can be solved by anyone. I was thinking if its possible to add a label when an issue receives certain number of thumbs up  showing that many users are facing this issue . 
The maintainers would be able to sort the issues based on number of thumbs up , making the list priority wise and thus reducing noise .
Let me know if this sounds like a good idea .

**Comment by j-f1** [comment]
How about 👍 - 👎 as the criterion?

**Comment by vaibhavchellani** [comment]
yes , but i had thought of putting a label on the issue according to the number of thumbs up , so that we can directly search using the label .

**Comment by j-f1** [comment]
@vaibhavchellani There is a way to sort by number of 👍 reactions: [`sort:reactions-+1-desc`](https://github.com/probot/ideas/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by j-f1** [comment]
You can also sort by total number of reactions: [`sort:reactions-desc`](https://github.com/probot/ideas/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-desc).

**Comment by vaibhavchellani** [comment]
okay thanks ! i think i can close this then .
