### ISSUE TITLE
idea: semantic pull request titles

### ISSUE THREAD

**Issue by zeke** [probot/ideas#48]
Yo, proboteers! 🙌 

We're using semantic-release all over the @electron org, and we want to start putting more checks into place to prevent accidentally shipping pull requests that are missing semantic commit messages. Occasionally we end up having to open fake PRs with zero changes just to trigger a release.

@groundwater had a cool idea about how to solve this: What if we could just require that the PR title itself follows semantic conventions? Contributors can more easily update a PR title than they can retroactively edit existing commit messages.

As long the "squash" or "merge commit" PR merging style is being used this would work, right?

This seems like a probot candidate, right?

**Comment by gr2m** [comment]
>  Contributors can more easily update a PR title than they can retroactively edit existing commit messages

I usually use the squash & merge button if the commit messages don’t follow the commit conventions. 

I don’t think that semantic-release is looking at the title of a pull request at all, it only looks at commit messages right now

**Comment by zeke** [comment]
> I usually use the squash & merge button if the commit messages don’t follow the commit conventions.

That's what we do too, but we have dozens of contributors so it's harder to spread the lore.

> I don’t think that semantic-release is looking at the title

Does it matter if semantic-release is looking at the title? If merging or squashing, the PR title becomes the default commit message.

**Comment by j-f1** [comment]
> it's harder to spread the lore

You could always disable all of the other merge options :)

**Comment by zeke** [comment]
> disable all of the other merge options :)

We've talked about that, but everyone has a special case where one flavor of merging is more appropriate. In any case, even if we did disable the other options, it still wouldn't actually check that the PR title is semantic.

**Comment by zeke** [comment]
Work in progress: https://github.com/probot/semantic-pull-requests

Works on my machine!

Failing:

<img width="802" alt="screen shot 2018-02-26 at 3 52 35 pm" src="https://user-images.githubusercontent.com/2289/36702733-27eb8a82-1b0d-11e8-946f-8697af711592.png">

---

Prepend "fix: " to the title and now it's passing. 🎉 

<img width="792" alt="screen shot 2018-02-26 at 3 51 18 pm" src="https://user-images.githubusercontent.com/2289/36702753-41bba29e-1b0d-11e8-9de3-380237dbb071.png">

**Comment by IAmHughes** [comment]
Just came by to say that this seems like a welcomed addition, 👍 🎉

**Comment by zeke** [comment]
Thanks, @IAmHughes. We may have a publicly installable version of this pretty soon. Stay tuned.

**Comment by pjurczynski** [comment]
(psst. - it's already here: https://probot.github.io/apps/semantic-pull-requests/ ) GJ guys, thanks!

**Comment by zeke** [comment]
Thanks for following up @pjurczynski. Yeah this is totally a thing now!

Used by orgs like Electron, Probot, Nuxt, and Algolia! 🙌
