### ISSUE TITLE
Notify mentor about ignored issues and pull requests

### ISSUE THREAD

**Issue by AkshitKrNagpal** [probot/ideas#59]
**Problem**
Every time a new issue is reported or new pull request is submitted, owners receive a notification but sometimes they forget to review and reply.

**Solution**
A bot can be made that notify the owner if the issue or pull request is open for a specified period of time with no response from him. The bot can make a comment in issue/PR with owner mentioned in the comment. This will remind the owner to review it.

**Comment by gr2m** [comment]
Is that something you could do with the stale app? https://github.com/apps/stale

**Comment by AkshitKrNagpal** [comment]
I don't think stale currently notify owners. Maybe this can be built on top of that?

**Comment by j-f1** [comment]
@AkshitKrNagpal You could put a custom message in the config that pings people.

**Comment by AkshitKrNagpal** [comment]
Yeah... I guess this can be configured using the stale app.
I'll close this.
Thanks
