### ISSUE TITLE
An app that update dependencies of Node.js app

### ISSUE THREAD

**Issue by abhijeetps** [probot/ideas#66]
**Problem**
 Dependencies of applications on Node.js hosted on GitHub are usually out of date and not updated. 

**Solution**
We have a npm package [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) which updates dependencies of package.json for Node.js.

It would be great to have a Probot app which updates file `package.json` creating an issue and commenting something like (check if the issue is by maintainer):

`\update package.json`

The bot will do a regex search in it, check if the issue is by a maintainer, create a branch, commit changes by running `ncu -u` and create a pull.

Of course, the bot will be subscribed to the required events. 

I am currently working on this. 😄

**Comment by aps120797** [comment]
I think the bot will be really useful, and would be liked by all Node.js developers who have hosted their application. Also, a similar app could be made for Python or some other platforms, where the app is depended on some external dependencies and maintains a file somewhat similar to package.json

**Comment by maracuja-juice** [comment]
It's not a Probot bot but this is exactly what [Greenkeeper](https://github.com/greenkeeperio/greenkeeper) does.

**Comment by aps120797** [comment]
Oh, didn't knew that.
My bad, I will still experiment how this goes with Probot. 😄

**Comment by gr2m** [comment]
Greenkeeper totally could use Pronto I think :) but it’s a much more complex project than most of the probot apps out there

**Comment by aps120797** [comment]
Hey @gr2m , I searched for it but couldn't find info related to this. What's Pronto? Is it something similar to Probot?
Can you please share a URL?

**Comment by maracuja-juice** [comment]
@aps120797 not sure but it could be this right here: https://github.com/prontolabs/pronto

As far as I know though they don't use that.

**Comment by aps120797** [comment]
Yeah, I too saw that. I saw this also: https://github.com/express-vue/vue-pronto
But I think both of these are not used by greenkeeper.
Not sure what it is.

I investigated https://github.com/greenkeeperio/greenkeeper/blob/master/package.json, but couldn't find anything related.

**Comment by maracuja-juice** [comment]
@aps120797 I think it's all built by them. Look here: https://github.com/greenkeeperio/changes
Also at the bottom of their readme there's a documentation.

**Comment by gr2m** [comment]
Lol sorry folks I meant pro it, not pronto. Autocorrect on the phone :D

**Comment by Berkmann18** [comment]
It's been done alreaday by [dependabot](https://github.com/marketplace/dependabot).

**Comment by ianwalter** [comment]
Also check out [Renovate](https://github.com/renovatebot/renovate) if you haven't yet. It's not just a service but also an open source project you can run yourself unlike Greenkeeper and Dependabot.

**Comment by okyanusoz** [comment]
And [Dependabot](https://dependabot.com) by GitHub.

**Comment by gr2m** [comment]
yeah I think we can close this issue :)
