### ISSUE TITLE
My idea is about a space for children, full of code and chocolate!

### ISSUE THREAD

**Issue by Chococoin** [probot/ideas#89]
Hi people, 

I'm studying to build a place called chocosfera.com. I'm designing the chocosfera as a space to help children develop their potential in a loving environment. 

My main idea is teaching git and GitHub creating a collective tale. The tale of this universe called Chocosfera. 

At the beginning, we'll have only a few lines of the tale in a commit. Is about a character that eats Chocolate and sees telestrasport itself to this great but unknown place. We'll continue the story with some few characters, but the idea is that every "Choconaut" could create a character, first drawing it, and then from the fork of the first commit continue a parallel story with his/her character. 

In any case my project is huge. As you could see in my current repo I'm developing a standalone app with an electron. Because I want to use a raspberry as "terminal" or a "node" where the children will have all kind of experiences with code, music, art, and chocolate. 

We have too a cryptocurrency called "Chococoin", and I'm working to change the algorithm of consensus from "Proof-of-work" to "Proof-of-tree". Because we don't want children to mine Chococoin as the bitcoin is mined. The chococoin will be only a tool to teach code and pay to children rewards for the art they will post in the platform. 

Is somebody is interested I may give more details.

I think that with probot I could develop the management of the commits inside an electron enviroment.

Best regard and thank you for reading.

https://github.com/Chococoin/CrystalChocolate

**Comment by Jme7** [comment]
Hi! I like your idea, so I would like to help out! I don't know how much of a help I will be, I am not a exactly an expert, but I work for free (I am serious, DON'T PAY ME ANYTHING). If you need any help, just bring up an issue, and "mention @Jme7".

**Comment by Jme7** [comment]
I like this idea, so I will be available if you need me. I don't know how much I will help, but I work for free (seriously, don't pay me for helping with bounties OR ANYTHING). If you want help, just mention @Jme7 (I will probably get to it in at most 3 days, but probably less)

**Comment by Jme7** [comment]
And I like your character, Kocao.

**Comment by Chococoin** [comment]
Hi @Jme7, I saw today your messagge minutes. Thanks for your offer of help I'll be glade to work with you. Let's keep in touch.

**Comment by Jme7** [comment]
Ok! Again, just say "@Jme7" to contact me.
