### ISSUE TITLE
Keep pull request branches up to date

### ISSUE THREAD

**Issue by zeke** [probot/ideas#99]
I work on a fairly large project that ships several times a day. We have a branch protection setting enabled on the repo:

<img width="693" alt="Screen Shot 2019-08-28 at 1 10 55 PM" src="https://user-images.githubusercontent.com/2289/63889164-4d8e6b00-c995-11e9-8b7e-e7508aab7a4a.png">

---

Because of this setting, we see this a lot:

---

<img width="678" alt="Screen Shot 2019-08-28 at 1 09 26 PM" src="https://user-images.githubusercontent.com/2289/63889203-5d0db400-c995-11e9-8e52-9e9937e35642.png">

---

Sometimes we have several pull requests that are green, reviewed, and ready to go. But merging one of them means all the others fall behind, and have to updated one at a time, and we have to wait for all checks to run and pass again.

I think it would be cool if there was a Probot app for this. It would keep an eye on all PRs that are passing all their checks, and keep them updated with their base branch when it's updated. Does such a thing exist? If not, maybe we should build it! We could call it... The FreshMaker.

**Comment by rsarky** [comment]
This sounds cool!
Might take take a stab at this if this hasn't been done before

**Comment by zeke** [comment]
Hey @rsarky! If you do work on this, please let me know. I'd be happy to help on it.

**Comment by Jme7** [comment]
Just wondering, 11 months and 1 day later, has this been made? This looks like an AMAZING app, and I want to try it!

**Comment by zeke** [comment]
I did a quick search and found this GitHub Action for keeping branches up to date: https://github.com/marketplace/actions/auto-update -- haven't used it before but it might do the trick.

**Comment by Jme7** [comment]
Thanks! I was actually doubting that anyone would respond, but I figured I might as well ask. So thank you!!

**Comment by zeke** [comment]
I'm going to go ahead and close this issue, as GitHub Actions has become the de facto product for solving workflow problems of this nature.

**Comment by Jme7** [comment]
Ok
